import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ApolloProvider } from "@apollo/client";
import appolloClient from "../apollo-client";
import { onError } from "@apollo/client/link/error";
import Head from "next/head";
import { useEffect } from "react";
import { NetworkContextProvider } from "../context/NetworkContext";
import ConnectionListener from "../components/ConnectionListener";

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.forEach(({ message, locations, path }) =>
      console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
    );
  if (networkError) console.log(`[Network error]: ${networkError}`);
});

function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    navigator.serviceWorker
      .register("/sw.js")
      .then(registration =>
        console.log("Service Worker registration successful with scope: ", registration.scope)
      )
      .catch(err => console.log("Service Worker registration failed: ", err));
  }, []);

  return (
    <>
      <Head>
        <title>Golf Stat Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <ApolloProvider client={appolloClient}>
        <NetworkContextProvider>
          <Component {...pageProps} />
          <ConnectionListener />
        </NetworkContextProvider>
      </ApolloProvider>
    </>
  );
}

export default MyApp;
