import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "../apollo-client";
import Head from "next/head";
import { NetworkContextProvider } from "../context/NetworkContext";
import { AuthContextProvider } from "../context/AuthContext";
import ConnectionListener from "../components/ConnectionListener";
import Nav from "../components/Nav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthPersist from "../components/AuthPersist";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Golf Logs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <ApolloProvider client={apolloClient}>
        <AuthContextProvider>
          <NetworkContextProvider>
            <Nav />
            <Component {...pageProps} />
            <ToastContainer
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable={false}
              pauseOnHover={false}
              theme="light"
            />
            <ConnectionListener />
            <AuthPersist />
          </NetworkContextProvider>
        </AuthContextProvider>
      </ApolloProvider>
    </>
  );
}

export default MyApp;
