import { Box, Button, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import GolfCourseRoundedIcon from "@mui/icons-material/GolfCourseRounded";
import Link from "next/link";
import { useRouter } from "next/router";
import useMediaQuery from "../components/useMediaQuery";
import ImageCard from "../components/ImageCard";
import { landingPageContent } from "../content/LandingPage";
import Card from "@mui/material/Card";

const cards = ["Bag", "Signal"];

const Home: NextPage = () => {
  const router = useRouter();
  const isMobile = useMediaQuery(600);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <Box textAlign="center" my={3}>
        <Typography variant="h5">Go low with</Typography>
        <Typography variant="h2">Golf Logs</Typography>
        <hr style={{ maxWidth: isMobile ? "85%" : "25%" }} />
        <Box my={3}>
          <Typography variant="h6">Create Golfer Account</Typography>
          <Box mt={1} mb={2}>
            <Button
              onClick={() => router.push("/register")}
              size="medium"
              variant="contained"
              color="primary"
            >
              Register
            </Button>
          </Box>
          <Link href="/login">
            <a>
              <Typography variant="subtitle2">
                Already have an account?&nbsp;
                <u>Login</u>
              </Typography>
            </a>
          </Link>
        </Box>
        <Card
          sx={{
            margin: "auto",
            maxWidth: isMobile ? "100%" : "50%",
            padding: 5,
            boxShadow: 3,
          }}
        >
          <Box my={3}>
            <GolfCourseRoundedIcon sx={{ fontSize: 150 }} />
          </Box>
          <Typography variant="h6">Do more than keep score</Typography>
          <Box textAlign="left" mt={2}>
            <Typography variant="body1">
              Keep track of every single shot with Golf Logs. Record the club used, distance to pin
              and shot result to create a snapshot of each stroke. Golf Logs will help you learn
              your club distances, see your mishit tendancies and allow you to better understand
              your strengths on the golf course.
            </Typography>
          </Box>
        </Card>
        {landingPageContent.map(card => {
          return (
            <ImageCard
              key={card.title}
              title={card.title}
              image={card.image}
              alt={card.alt}
              value={card.value}
              buttonOneText={card.buttonOneText}
              buttonTwoText={card.buttonTwoText}
            />
          );
        })}
      </Box>
    </div>
  );
};

export default Home;
