import { IRoundPreview, pieStatKeys } from "../pages/[username]/profile";
import { getScoreCountByName } from "../utils/holeDetailsFormatter";
import { scoreCountByNameArray } from "../utils/statChartHelpers";

// TODO
test("Should return count of scores by name like par, birdie etc.", () => {
  const parArray = [
    "4",
    "4",
    "4",
    "4",
    "3",
    "5",
    "4",
    "3",
    "4",
    "35",
    "4",
    "4",
    "4",
    "4",
    "3",
    "5",
    "4",
    "3",
    "4",
    "35",
  ];

  const holeScores = [
    2,
    3,
    4,
    5,
    5,
    8,
    8,
    1,
    4,
    45,
    2,
    3,
    4,
    5,
    5,
    8,
    8,
    1,
    4,
    44,
    89,
    null,
    null,
    null,
    null,
  ];
  const holeScores1 = [
    4,
    4,
    3,
    4,
    null,
    null,
    null,
    null,
    10,
    25,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    25,
    null,
    null,
    null,
    null,
  ];
  const holeScores2 = [
    1,
    4,
    4,
    4,
    3,
    2,
    2,
    1,
    3,
    25,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    25,
    null,
    null,
    null,
    null,
  ];
  const holeScores3 = [
    5,
    6,
    7,
    8,
    4,
    7,
    7,
    6,
    9,
    25,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    25,
    null,
    null,
    null,
    null,
  ];
  const holeScores4 = [
    5,
    6,
    7,
    8,
    4,
    7,
    7,
    6,
    9,
    4,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    25,
    null,
    null,
    null,
    null,
  ];
  const holeScores5 = [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    0,
    0,
    null,
    null,
    null,
    null,
  ];

  const test = getScoreCountByName(holeScores, parArray);
  const test1 = getScoreCountByName(holeScores1, parArray);
  const test2 = getScoreCountByName(holeScores2, parArray);
  const test3 = getScoreCountByName(holeScores3, parArray);
  const test4 = getScoreCountByName(holeScores4, parArray);
  const test5 = getScoreCountByName(holeScores5, parArray);

  expect(test).toEqual({
    ace: 2,
    albatross: 0,
    eagle: 2,
    birdie: 2,
    parCount: 4,
    bogey: 2,
    doubleBogey: 2,
    tripleBogey: 2,
    quadBogeyOrWorse: 2,
  });
  expect(test1).toEqual({
    ace: 0,
    albatross: 0,
    eagle: 0,
    birdie: 1,
    parCount: 3,
    bogey: 0,
    doubleBogey: 0,
    tripleBogey: 0,
    quadBogeyOrWorse: 1,
  });
  expect(test2).toEqual({
    ace: 1,
    albatross: 2,
    eagle: 1,
    birdie: 1,
    parCount: 4,
    bogey: 0,
    doubleBogey: 0,
    tripleBogey: 0,
    quadBogeyOrWorse: 0,
  });
  expect(test3).toEqual({
    ace: 0,
    albatross: 0,
    eagle: 0,
    birdie: 0,
    parCount: 0,
    bogey: 2,
    doubleBogey: 2,
    tripleBogey: 3,
    quadBogeyOrWorse: 2,
  });
  expect(test4).toEqual({
    ace: 0,
    albatross: 0,
    eagle: 0,
    birdie: 0,
    parCount: 0,
    bogey: 2,
    doubleBogey: 2,
    tripleBogey: 3,
    quadBogeyOrWorse: 2,
  });
  expect(test5).toEqual({
    ace: 0,
    albatross: 0,
    eagle: 0,
    birdie: 0,
    parCount: 0,
    bogey: 0,
    doubleBogey: 0,
    tripleBogey: 0,
    quadBogeyOrWorse: 0,
  });
});

test("Should return an array of length 9 with each index corresponding to the count of a golf score by name. For use in pie chart", () => {
  const roundPreviews: IRoundPreview[] = [
    {
      ace: 0,
      albatross: 0,
      birdie: 2,
      bogey: 3,
      course_id: "f242206c-d215-4024-83d9-aba6d533050c",
      course_name: "Hancock Austin Mun Golf Club (Front 9)",
      double_bogey: 0,
      eagle: 0,
      fairwaysHit: "0/14",
      greensInReg: 0,
      is_user_added_course: false,
      par: 8,
      quadruple_bogey_or_worse: 0,
      round_date: "1/15/2023, 10:53:56 AM",
      round_id: "048ea2e8-1a8d-4b27-9c22-c31dca8299b6",
      score: 58,
      tee_color: "blue",
      threePutts: 0,
      totalPutts: 0,
      triple_bogey: 1,
      unverified_course_id: "",
    },
  ];
  const case1 = scoreCountByNameArray(roundPreviews, pieStatKeys);
  expect(Array.isArray(case1)).toEqual(true);
  expect(case1.length).toEqual(9);
  expect(case1).toEqual([0, 0, 0, 2, 8, 3, 0, 1, 0]);
  // TODO add more tests here
//   expect(scoreCountByNameArray(roundPreviews, pieStatKeys)).toEqual([0, 0, 0, 2, 8, 3, 0, 1, 0]);
});

//   const holeShotDetails: IShotDetail[][] = [
//     [
//       { shotNumber: 1, distanceToPin: 289, club: "8 iron", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 140, club: "9 iron", result: "Mishit" },
//       { shotNumber: 3, distanceToPin: 85, club: "Pitching Wedge", result: "Miss Left" },
//       { shotNumber: 4, distanceToPin: 35, club: "Pitching Wedge", result: "Miss Long" },
//       { shotNumber: 5, distanceToPin: 35, club: "56 degree", result: "Miss Long" },
//       { shotNumber: 6, distanceToPin: 10, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 7, distanceToPin: 24, club: "Putter", result: "Miss Short" },
//       { shotNumber: 8, distanceToPin: 8, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 454, club: "Driver", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 240, club: "4 hybrid", result: "Mishit" },
//       { shotNumber: 4, distanceToPin: 45, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 200, club: "4 hybrid", result: "Miss Short" },
//       { shotNumber: 5, distanceToPin: 15, club: "Putter", result: "Miss Long" },
//       { shotNumber: 6, distanceToPin: 5, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 365, club: "7 iron", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 130, club: "Pitching Wedge", result: "Mishit" },
//       { shotNumber: 3, distanceToPin: 55, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 4, distanceToPin: 39, club: "Putter", result: "Miss Short" },
//       { shotNumber: 5, distanceToPin: 18, club: "Putter", result: "Miss Right" },
//       { shotNumber: 6, distanceToPin: 7, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 135, club: "Pitching Wedge", result: "Miss Left" },
//       { shotNumber: 2, distanceToPin: 25, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 14, club: "Putter", result: "Miss Short" },
//       { shotNumber: 4, distanceToPin: 4, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 307, club: "8 iron", result: "Miss Right" },
//       { shotNumber: 2, distanceToPin: 90, club: "Pitching Wedge", result: "Hit Fairway" },
//       { shotNumber: 3, distanceToPin: 90, club: "56 degree", result: "Miss Right" },
//       { shotNumber: 4, distanceToPin: 20, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 5, distanceToPin: 20, club: "Putter", result: "Miss Long" },
//       { shotNumber: 6, distanceToPin: 2, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 342, club: "8 iron", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 120, club: "56 degree", result: "Miss Short" },
//       { shotNumber: 3, distanceToPin: 25, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 4, distanceToPin: 7, club: "Putter", result: "Miss Long" },
//       { shotNumber: 5, distanceToPin: 1, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 144, club: "9 iron", result: "Miss Right" },
//       { shotNumber: 2, distanceToPin: 30, club: "56 degree", result: "Mishit" },
//       { shotNumber: 3, distanceToPin: 30, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 4, distanceToPin: 30, club: "Putter", result: "Miss Long" },
//       { shotNumber: 5, distanceToPin: 13, club: "Putter", result: "Miss Long" },
//       { shotNumber: 6, distanceToPin: 1, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 446, club: "Driver", result: "Miss Left" },
//       { shotNumber: 2, distanceToPin: 225, club: "4 hybrid", result: "Miss Right" },
//       { shotNumber: 4, distanceToPin: 45, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 45, club: "56 degree", result: "Mishit" },
//       { shotNumber: 5, distanceToPin: 69, club: "Putter", result: "Miss Long" },
//       { shotNumber: 6, distanceToPin: 10, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 270, club: "7 iron", result: "Miss Right" },
//       { shotNumber: 2, distanceToPin: 155, club: "Pitching Wedge", result: "Mishit" },
//       { shotNumber: 3, distanceToPin: 120, club: "Pitching Wedge", result: "Hit Green" },
//       { shotNumber: 4, distanceToPin: 13, club: "Putter", result: "In Hole" },
//     ],
//     [{ fairwaysHit: "4/7", greensInReg: 0, threePutts: 2, totalPutts: 19 }],
//     [
//       { shotNumber: 1, distanceToPin: 267, club: "9 iron", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 95, club: "56 degree", result: null },
//       { shotNumber: 3, distanceToPin: 30, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 4, distanceToPin: 30, club: "Putter", result: "Miss Short" },
//       { shotNumber: 5, distanceToPin: 5, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 310, club: "Driver", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 70, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 49, club: "Putter", result: "Miss Short" },
//       { shotNumber: 4, distanceToPin: 10, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 435, club: "Driver", result: "Miss Left" },
//       { shotNumber: 2, distanceToPin: 210, club: "Pitching Wedge", result: "Hit Fairway" },
//       { shotNumber: 3, distanceToPin: 125, club: "Pitching Wedge", result: "Miss Left" },
//       { shotNumber: 4, distanceToPin: 40, club: "56 degree", result: "Mishit" },
//       { shotNumber: 5, distanceToPin: 45, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 6, distanceToPin: 13, club: "Putter", result: "Miss Long" },
//       { shotNumber: 7, distanceToPin: 1, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 111, club: "52 degree", result: "Miss Short" },
//       { shotNumber: 2, distanceToPin: 20, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 9, club: "Putter", result: "Miss Short" },
//       { shotNumber: 4, distanceToPin: 4, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 335, club: "Driver", result: "Miss Left" },
//       { shotNumber: 2, distanceToPin: 335, club: "Pitching Wedge", result: "Mishit" },
//       { shotNumber: 3, distanceToPin: 335, club: "4 hybrid", result: "Miss Left" },
//       { shotNumber: 4, distanceToPin: 175, club: "7 iron", result: "Miss Left" },
//       { shotNumber: 5, distanceToPin: 65, club: "Pitching Wedge", result: "Hit Green" },
//       { shotNumber: 6, distanceToPin: 32, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 100, club: "52 degree", result: "Hit Green" },
//       { shotNumber: 2, distanceToPin: 30, club: "Putter", result: "Miss Short" },
//       { shotNumber: 3, distanceToPin: 6, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 376, club: "7 iron", result: "OB" },
//       { shotNumber: 2, distanceToPin: 250, club: null, result: "Penalty Stroke" },
//       { shotNumber: 3, distanceToPin: 255, club: "Pitching Wedge", result: "Hit Fairway" },
//       { shotNumber: 4, distanceToPin: 155, club: "8 iron", result: "Miss Long" },
//       { shotNumber: 5, distanceToPin: 30, club: "56 degree", result: "Mishit" },
//       { shotNumber: 6, distanceToPin: 15, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 7, distanceToPin: 34, club: "Putter", result: "Miss Long" },
//       { shotNumber: 8, distanceToPin: 1, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 159, club: "7 iron", result: "Miss Left" },
//       { shotNumber: 2, distanceToPin: 25, club: "56 degree", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 5, club: "Putter", result: "Miss Right" },
//       { shotNumber: 4, distanceToPin: 5, club: "Putter", result: "In Hole" },
//     ],
//     [
//       { shotNumber: 1, distanceToPin: 291, club: "Driver", result: "Hit Fairway" },
//       { shotNumber: 2, distanceToPin: 19, club: "Putter", result: "Hit Green" },
//       { shotNumber: 3, distanceToPin: 19, club: "Putter", result: "Miss Short" },
//       { shotNumber: 4, distanceToPin: 6, club: "Putter", result: "In Hole" },
//     ],
//     [{ fairwaysHit: "3/6", greensInReg: 3, threePutts: 1, totalPutts: 18 }],
//     [{ fairwaysHit: "7/13", greensInReg: 3, threePutts: 3, totalPutts: 37 }],
//     [{ shotNumber: 1, distanceToPin: null, club: null, result: null }],
//     [{ shotNumber: 1, distanceToPin: null, club: null, result: null }],
//     [{ shotNumber: 1, distanceToPin: null, club: null, result: null }],
//     [{ shotNumber: 1, distanceToPin: null, club: null, result: null }],
//   ];
